# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  assume_role:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Generate Assumed Role Credentials
          command: |
            env >> .env
            mkdir .secrets
            docker run --env-file .env brutalsimplicity/cicd-tools:latest aws-assume --role $DEPLOYMENT_ROLE -e >> .secrets/.env

      - persist_to_workspace:
          root: '.'
          paths:
            - .secrets

  verify:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Verify Credentials
          working_directory: /tmp/workspace
          command: |
            $(cat .secrets/.env)
            aws sts get-caller-identity

workflows:
  build:
    jobs:
      - assume_role:
          name: Assume AWS Deployment Role
          context: cloud-magix
      - verify:
          requires:
            - Assume AWS Deployment Role
          name: Verify Assume Role
