# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  assume_role:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: aws-assume Help
          command: |
            $(aws-assume --role $DEPLOYMENT_ROLE -e)
            env
            aws s3 ls

workflows:
  build:
    jobs:
      - assume_role:
          name: Assume AWS Deployment Role
          context: cloud-magix
