# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  assume_role:
    docker:
      - image: brutalsimplicity/cicd-tools:v1.0.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: aws-assume Help
          command: |
            $(aws-assume --role $DEPLOYMENT_ROLE -e)
            env
            aws s3 ls

workflows:
  build:
    jobs:
      - assume_role:
          name: Assume AWS Deployment Role
          context: cloud-magix
